### ISSUE TITLE
[Optimization]Upload stopped when file manager is closed

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#103]
## Optimization Needed
Can files upload still run in background when the file manager is closed and display an upload progress bar?

**Comment by tobychui** [comment]
This cannot be fixed because the whole upload routine is developed on top of the File Manager (so it can be used separately as a WebApp or desktop app). In fact, different apps (e.g. Desktop) have their own upload routine optimize for that particular use cases, and each webapp handles their own upload stream and lists. 

As always, PR are welcomed 👍🏻
