### ISSUE TITLE
Is there a Demo page?

### ISSUE THREAD

**Issue by syxanash** [tobychui/arozos#177]
Hi your project is impressive I really liked going through the source code, I was wondering is there a demo page available somewhere?
I would love to feature your project on a web directory I maintain called [Web Desktops](https://simone.computer/webdesktops)

**Comment by tobychui** [comment]
Hey @syxanash 

There isn't, because it can't be done with the current available resources. 

The uniqueness of ArozOS, compare to other web desktop projects out there, is that it has a full storage architecture including virtual file system layers, disk management and so on comes with it. So it is not possible to detach only the "Web desktop" section of the system from what underneath and make it a "Demo". It can be done, but it will be really costly involving setting up each visitor a VM somewhere on the cloud. As this project is purely funded by myself, it is currently not financially viable for me to do that.  

If you want to try it out, you can download the web.tar.gz and the binary file, put it inside a RAM disk space and start it on Windows (it will enter guest mode with limited hardware management features that mostly READ from your system instead of writing anything to it) or Raspberry Pi (Linux, with full control, but you can flash the SD card easily if you don't like it).

**Comment by syxanash** [comment]
Thank you for clarifying @tobychui your project really is amazing, good luck with the development!
