### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by lvagabond** [tobychui/arozos#20]
Hi, would it be possible to add a Samba server?
Or add the function of simply sharing the root directory or separate folders to the network? And if he went to assign access to the  folder, it would be absolutely great.

**Comment by tobychui** [comment]
One of the reason that we got stuck in implementing Samba on arozos is that we still can't figure out how to mange user storage quota for files uploaded via smb protocol. We will try to implement this feature once with get this figured out.

**Comment by tobychui** [comment]
![2020-11-21_10-31-41](https://user-images.githubusercontent.com/24617523/99872480-e2295c80-2c1c-11eb-99b1-69b3a79b069c.png)

The samba function has been added as a sub-service in the arozos v1.107. Image file will be release once it has completed it internal testing. 

**User quota management might not works if the user has limited storage quota and have samba sub-service enabled. This (hopefully) will be fixed in future updates.**
