### ISSUE TITLE
[Feature request] RAID Management 

### ISSUE THREAD

**Issue by jivank** [tobychui/arozos#29]
**Describe the solution you'd like**
Ability to create LVM, BTRFS or ZFS from disks.
Would this be better suited as a Subservice? If so, is there any documentation for setting up one?

**Comment by tobychui** [comment]
I am wondering if these disk management features are truly necessary. As this is an OS design for general purpose cloud computing instead of acting as a storage management system (or NAS OS). 

It might be more suitable for Sub-service. If you are interested in developing one, please take a look at the subservice demo module
https://github.com/aroz-online/ArozOS-Subservice-Example

**Comment by yeungalan** [comment]
I believe zfs or btrfs is still a necessity for uptime in a high-performance computing system. As both filesystems could provide snapshot or self-healing, that could guarantee the system won't be crash easily.

**Comment by tobychui** [comment]
> I believe zfs or btrfs is still a necessity for uptime in a high-performance computing system. As both filesystems could provide snapshot or self-healing, that could guarantee the system won't be crash easily.

What you are saying is true. However, I am busy working on the system core in these period of time. @yeungalan can you help pick one and start work on it first? You can start by adding a new zfs or btrfs module in file system under mod/filesystem.

I will assign this improvement work to you, thanks!
