### ISSUE TITLE
Invalid Interface Module

### ISSUE THREAD

**Issue by luozhiwenchn** [tobychui/arozos#39]
You are seeing this message because the administrator of this system has removed all your interfacing modules. Please contact technical support and show them this page.

ERROR: INVALID-INTERFACE-MODULE-SETTINGS

Just after the first registration

**Comment by tobychui** [comment]
Thanks for the feedback. Please provide more information on:

1. Which method you are using to deploy the ArozOS (build from source or binary?)
2. What platform and CPU architecture are you using?
3. On which version of ArozOS that you see this error?

This usually happens when you upgraded the system without deleting the database. (The database structure are still changing constantly, if you are using it for production, please wait for a stable release)

Some internal developers also feedback this issue to me few weeks ago and this usually get resolved by deleting the ao.db under system/ and restarting the system.

If you still encounter this error after restarting your ArozOS binary, try

1. Deleting the ao.db under system/ and restart ArozOS
2. Try a different username with only ASCII characters
3. Update the ArozOS to the latest version (using build from source method)

**Comment by luozhiwenchn** [comment]
Thanks for your reply.

arozos_v1.107.img
3b+

I have reflashed the tf card. But it is strange that the website cannot be open normally now. Only the topic "ArOZ Online Bootloader" can be seen.

**Comment by luozhiwenchn** [comment]
![image](https://user-images.githubusercontent.com/73952869/104031593-dc58fc00-5207-11eb-9703-3cef1b25650e.png)
![image](https://user-images.githubusercontent.com/73952869/104031643-f266bc80-5207-11eb-9e63-3c04fb78da72.png)
Where to find  ao.db under system/

@tobychui

**Comment by tobychui** [comment]
@luozhiwenchn  If you are using a Raspberry pi as host, you should be able to see the ao.db in ```/home/pi/arozos/system/```.

If you are seeing "ArOZ Online Bootloader" on your browser, this is usually cause by browser caching the login session while you have re-installed the system on the same Host with the same IP address. You can try to clear cookie on the site or using the logout API to clear the cache on your browser. In simple words, you can visit the following URL: 
```
http://{your_raspberry_pi_ipaddr}:{port}/system/auth/logout
```
**Example**
```
http://192.168.0.100:80/system/auth/logout
```

After seeing ```OK```, restart the browser and try to login again. Your problem should be fixed by then.

**Comment by luozhiwenchn** [comment]
It bacame worse.
I did as you said.
But this time, the website cannot be open and nothing can be seen.

**Comment by tobychui** [comment]
I have no idea what is happening on your side. If that is the case, please wait for the coming v1.108 image. 

In the mean time, you can try build from source using Raspberry Pi OS or try to reinstall again and login with another browser.

**Comment by luozhiwenchn** [comment]
Hi.
I reflashed the card again. It makes a difference. But after the Login page, it will be Invalid Interface Module again

**Comment by tobychui** [comment]
That is interesting. Please email me at imuslab@gmail.com and I will see if I can guide you to debug the system step by step.
