### ISSUE TITLE
Raspberry Pi zero w installation

### ISSUE THREAD

**Issue by zufi110** [tobychui/arozos#54]
Hi
I downloaded arozos v1.109 and flash image on sdcard and then put card into pi zero. I am not Computer person. there is no arozos showing in Network Neighbourhood. also pi zero is not booting in desktop mode...Would you please tell me step by step installation and operating procedure for using Arozos on pi zero w? thanks

**Comment by tobychui** [comment]
Hi, your issue is not related to ArozOS and you should follow the standard Raspberry Pi Zero W headless setup method instead. You can follow Step 3 and 4 in the following guide:
https://desertbot.io/blog/headless-pi-zero-w-wifi-setup-windows

If you need help, feel free to join our telegram group (You can find the link in README - Community section) and ask questions in that group instead. Github issues are mainly for source code related bugs and feature requests. Have a nice day :)
