### ISSUE TITLE
Doesn't show Network  "ArozOS (ARxxx)" on Rpi 3b+

### ISSUE THREAD

**Issue by CrazyCoder009** [tobychui/arozos#58]
**Problem**

_If you are using Raspberry Pi as your host, you can download one of the images and flash the image into your SD card. You will find a new network device named "ArozOS (ARxxx)" pop up in your "Network Neighbourhood". Double click the icon and you will be redirected to the system Web setup interface. If you cannot find the new device in your network, you can also connect to the ArozOS directly via http://{raspberry_pi_ip_address}:8080/_

I downloaded the latest release of the image and burned it into my RPI's USB stick (I use a USB stick instead of a SDcard for booting) but it doesn't show any network called "ArozOS". No HDMI Output as well.

**To Reproduce**
1. Downloaded the latest arozos v1.111 (Stable) image.
2. extracted files, flashed into usb with Balena Etcher.
3. Connected the usb, booted up the Rpi.

**Expected behavior**
Expected to see "ArozOS" network pop up as a hotspot.

**Recieved behavior**
No network scanned named "ArozOS". Nor any HDMI output to do troubleshooting.

**Tried techniques**
- Connected LAN cables to laptop and rpi and Tried to directly hunt down the rpi ip address and connect as mentioned above _"http://{raspberry_pi_ip_address}:8080/"_ - No success
- Tried rebooting and Re-flashing - No success  
- Tried different ports - 8081,8080 - No success

**Host Information(Raspberry Pi):**
I downloaded direct image from the Russian link in Readme.
 - Arozos version 1.111 image
 - Raspberry Pi 3B+
 - Usb used (Sandisk 32 GB)

**Client Information(My laptop):**
 - OS: Pop!_OS 20.10 x86_64
 - Browser - Brave Browser (Version 1.24.55 Chromium: 90.0.4430.51 (Official Build) beta (64-bit))

**Additional context**
Please tell me if I am doing anything wrong. May seem like a issue from my side.

**Comment by tobychui** [comment]
Hi @CrazyCoder009 , the image we provided for Raspberry Pi are not tested on Rpi 3B+. But I guess it won't be a problem as our image is based on the latest version of Raspberry Pi OS and it should be compatible with older version of Pis. 

In normal situation, the HDMI will output the Raspberry Pi terminal instead of "nothing" as mentioned in your issue and I am pretty sure port 8080 is the default port used in the v1.111 image. So I am guessing there is something wrong in your boot method / setups. 

There are a few things you can try:
1. Debug your booting device / method by observing the LED blink on the Rpi. You can easily find post about "Raspberry pi unable to boot" on the Raspberry Pi forum.
2. You can try building ArozOS from source after you have successfully deployed a Raspberry Pi OS on your USB drive and boot from it. A few extra steps will be needed but it is not difficult if you know how to use git clone, wget and execute shell scripts. You can take a look at the build from source instruction for other ARM SBC or just get one of the binary from the release page. 

I can help you out through the build from source process if needed. Feel free to contact me via email / telegram or leave your updates in this issue. Thank you!

**Comment by CrazyCoder009** [comment]
> Hi @CrazyCoder009 , the image we provided for Raspberry Pi are not tested on Rpi 3B+. But I guess it won't be a problem as our image is based on the latest version of Raspberry Pi OS and it should be compatible with older version of Pis. 
> 
> In normal situation, the HDMI will output the Raspberry Pi terminal instead of "nothing" as mentioned in your issue and I am pretty sure port 8080 is the default port used in the v1.111 image. So I am guessing there is something wrong in your boot method / setups. 
> 
> There are a few things you can try:
> 1. Debug your booting device / method by observing the LED blink on the Rpi. You can easily find post about "Raspberry pi unable to boot" on the Raspberry Pi forum.
> 2. You can try building ArozOS from source after you have successfully deployed a Raspberry Pi OS on your USB drive and boot from it. A few extra steps will be needed but it is not difficult if you know how to use git clone, wget and execute shell scripts. You can take a look at the build from source instruction for other ARM SBC or just get one of the binary from the release page. 
> 
> I can help you out through the build from source process if needed. Feel free to contact me via email / telegram or leave your updates in this issue. Thank you!

Thank you for the help and instructions @tobychui , I'm building from the source right now as we speak, will update if any developments.

**Comment by CrazyCoder009** [comment]
Okay, so I tried building from source and it worked. I am running ArozOS v1.111, looks like it was a problem on my own part while flashing.

Apart from that, the whole system is amazing! Again Thanks a lot and kudos for making this, I can easily manage my Rpi now. No more need for ssh or VNC or any kind of installations. To be honest, this is very underrated right now and I wish more people see this work. 

Sidenote: Another funny incident happened, while I was using the system I accidentally deleted the Trash Bin from desktop, although the icons are just shortcuts it was a quick fix.

![Screenshot from 2021-04-15 22-25-59](https://user-images.githubusercontent.com/41443510/114908303-9a100e00-9e39-11eb-85d4-ea8e0c407fb2.png)
![Screenshot from 2021-04-15 22-26-45](https://user-images.githubusercontent.com/41443510/114908417-b3b15580-9e39-11eb-8b6a-1483371d4b9c.png)
