### ISSUE TITLE
关于finding库时出现的问题

### ISSUE THREAD

**Issue by xiaoniu1234** [tobychui/arozos#59]
![image](https://user-images.githubusercontent.com/47274115/115383538-8af9d900-a208-11eb-8e64-377701ae3c1c.png)
看着这报错，我直接无语。
介于中国大陆的特殊网络环境，大家应该也清楚，毕竟世界墙国。
虽然中国大陆的网络环境较为特殊，但我在使用浏览器访问github时，除了某些图片无法加载，其它一切正常。
clone方面，除了速度较慢以外，也是一切正常。
所以我很疑惑，为什么自己clone的时候不会出现的time out问题，在编译时就偏偏会出现？我个人认为是timeout时长限制有点短，在中国大陆，连接到github的延迟高达288ms，而且经常会断开连接，延迟最高甚至能达到3000ms，丢包率高达67%，所以这是导致这个问题的根本原因。
就像python3里的urllib.urlretrieve一样，需要指定timeout时长，否则下载文件时很容易遇到time out错误。
希望能在以后的版本中改进，支持arozos！
那么，arozos是开源的，我为什么不自己进行更改？
嗯，我不会go，我只会python3和c++。

**Comment by tobychui** [comment]
Hi! @xiaoniu1234, thanks for opening this issue, This is not the problem of ArozOS. This is the issue caused by the Golang compiler trying to download the required dependencies. For solution, you can take a look at issue #55 .

你好，首先感謝你回報這錯誤。這並不是 ArozOS 的問題，而是由 Go 編譯器自動下載依賴而引起的。至於解決方法，請參閱 issue #55 。

I am also planning to add a python adaptive layer to ArozOS soon. If you are interested in working with us, feel free to contact us on Telegram or through email.

我之後亦有打算在 ArozOS 中增加一層 Python 轉譯層給予 Python 開發者開發適用於 ArozOS 的子服務。如果你有興趣一起研究的話歡迎加入我們的 Telegram 群組或直接透過電郵聯系我們。

Let me know if you still encountered any error after applying the fix mentioned in #55. Thanks.

如果你在嘗試 #55 內的方法後依然無法建置，請再留言 / 跟我聯系，謝謝。

**Comment by xiaoniu1234** [comment]
真好，我成功通过了以下命令解决了这个问题：
`export GOPROXY=https://goproxy.io`
希望这能帮助到更多人！
