### ISSUE TITLE
Media Center & Cloud OS Features

### ISSUE THREAD

**Issue by nsdanny2k** [tobychui/arozos#65]
As per Arozos docs, it was designed to be a Media Center.
Also, being a cloud os, Python support is indispensible.

**Comment by tobychui** [comment]
Hi @nsdanny2k, thanks for your new ideas.
Might I know what media center feature you want and what do you want to use Python for and which part do you think it fits the best? (e.g. Plugin / WebApp scripting? Reverse proxy support for python written web application?)

If you already have an Python written web application you want to merge into the ArozOS ,have you tried using the subservice module interface? 

Here is an example for integrating non-golang written web application into ArozOS using sub-service system and some bash script (Notes the .startscript, moduleInfo.json and start.sh file)
https://github.com/aroz-online/syncthing

**Comment by nsdanny2k** [comment]
To be honest i have been very busy trying to establish scooter business. But i had studied amazon web services at pluralsight and python lambda is the way to go for me as well as machine learning.With regards to media.... simple support for amazon prime, hbo max, spotify and youtube solves 90+ % of media support requirement.

    On Friday, June 18, 2021, 10:06:36 AM GMT+8, Toby Chui ***@***.***> wrote:  
 
 


Hi @nsdanny2k, thanks for your new ideas.
Might I know what media center feature you want and what do you want to use Python for and which part do you think it fits the best? (e.g. Plugin / WebApp scripting? Reverse proxy support for python written web application?)

If you already have an Python written web application you want to merge into the ArozOS ,have you tried using the subservice module interface?

Here is an example for integrating non-golang written web application into ArozOS using sub-service system and some bash script (Notes the .startscript, moduleInfo.json and start.sh file)
https://github.com/aroz-online/syncthing

**Comment by tobychui** [comment]
@nsdanny2k For machine learning, I don't think Raspberry Pi is a good platform for doing ML training with python. If you want to train & run tensorflow model, you can always train it on your desktop PC and use tensorflow.js which is more light-weighted to run it on the ArozOS using WebApp programming interfaces.

For your specific request for supporting amazon prime, spotify etc, unfortunately there is not much we can do because they are not open sourced. You might implement your own player for those web services but I am not sure if distributing such clients / webapps will or will not violate their user agreement. (In simple words, I don't want to get sue) 

Anyway, thanks for your suggestion and as always, any PR or fork are welcomed.

**Comment by nsdanny2k** [comment]
Yes thank you very much

Sent from Yahoo Mail on Android 
 
  On Fri, 18 Jun 2021 at 12:44 PM, Toby ***@***.***> wrote:   


Closed #65.
